const fs = require("fs");
const path = "src/components/research-workbench.tsx";
const u = (s) => s;
const lines = [];
const push = (...xs) => lines.push(...xs);
push('"use client";', "");
push('import { useMemo, useState } from "react";');
push('import { ReportDialog } from "@/components/report-dialog";');
push('import { ResearchCardItem } from "@/components/research-card-item";');
push('import { Badge } from "@/components/ui/badge";');
push('import { Button } from "@/components/ui/button";');
push("import {");
push("  Card,");
push("  CardContent,");
push("  CardDescription,");
push("  CardFooter,");
push("  CardHeader,");
push("  CardTitle,");
push('} from "@/components/ui/card";');
push('import { Input } from "@/components/ui/input";');
push('import { Label } from "@/components/ui/label";');
push('import { ScrollArea } from "@/components/ui/scroll-area";');
push('import { Separator } from "@/components/ui/separator";');
push('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";');
push('import { Textarea } from "@/components/ui/textarea";');
push('import { useResearchWorkbench } from "@/hooks/use-research-workbench";');
push('import { generateMockAiReport } from "@/lib/research-mock-ai";');
push("import {");
push("  buildFullMarkdownReport,");
push("  copyMarkdownToClipboard,");
push("  downloadMarkdown,");
push('} from "@/lib/research-markdown";');
push('import { clearWorkspaceStorage } from "@/lib/research-storage";');
push('import { cn } from "@/lib/utils";');
push("import {");
push("  AI_TOOLS,");
push("  LAYER_LABELS,");
push("  MODE_HINTS,");
push("  MODE_LABELS,");
push("  SOURCE_TOOL_LABELS,");
push("  STATUS_LABELS,");
push("  type AiToolId,");
push("  type CardLayer,");
push("  type CardStatus,");
push("  type ResearchMode,");
push("  type RunState,");
push("  type SourceTool,");
push('} from "@/types/research";');
push("");
push('const SOURCE_TOOLS: SourceTool[] = [');
push('  "chatgpt",');
push('  "gemini",');
push('  "claude",');
push('  "notebooklm",');
push('  "manual",');
push("];");
push("");
push('const MODES: ResearchMode[] = ["ACADEMIC", "BUSINESS", "ART"];');
push('const LAYERS: CardLayer[] = ["A", "B", "C"];');
push('const STATUSES: CardStatus[] = ["adopted", "pending", "rejected"];');
push("");
push("type DialogState = {");
push("  title: string;");
push("  description?: string;");
push("  content: string;");
push("} | null;");
push("");
push("function runStateBadge(state: RunState) {");
push("  switch (state) {");
push('    case "idle":');
push('      return <Badge variant="secondary">' + u("\u5F85\u6A5F") + "</Badge>;");
push('    case "running":');
push("      return (");
push('        <Badge className="bg-blue-600 text-white hover:bg-blue-600">' + u("\u8ABF\u67FB\u4E2D") + "</Badge>");
push("      );");
push('    case "done":');
push("      return (");
push('        <Badge className="bg-emerald-700 text-white hover:bg-emerald-700">' + u("\u5B8C\u4E86") + "</Badge>");
push("      );");
push("  }");
push("}");
push("");
push("function LayerEmpty({ layer }: { layer: CardLayer }) {");
push("  return (");
push('    <p className="py-6 text-center text-xs text-muted-foreground">');
push("      {layer}" + u("\u5C64\uFF08") + "{LAYER_LABELS[layer]}" + u("\uFF09\u306E\u30AB\u30FC\u30C9\u306F\u307E\u3060\u3042\u308A\u307E\u305B\u3093\u3002"));
push("    </p>");
push("  );");
push("}");
fs.writeFileSync("scripts/write-wb-partial.cjs", lines.join("\n"));
console.log("partial", lines.length);
